# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Copy the rest of the application code into the container at /app
COPY . /app/

# Expose port 8000 for the Django application
EXPOSE 8000

# Set the environment variables
ENV POSTGRES_USER=orders_user
ENV POSTGRES_PASSWORD=OrDeRs@123
ENV POSTGRES_DB=Sellings
ENV DB_HOST=db

# Start the Django application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
